server:
 port: 18080
spring:
 application:
  name: user
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/graduation?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
  username: root
  password: 123456

mybatis:
 type-aliases-package: com.wxy.pojo
 mapper-locations: classpath*:mappers/*.xml

#pagehelper分页插件配置
pagehelper:
 helper-dialect: mysql
 reasonable: true
 support-methods-arguments: true

thymeleaf:
 prefix: classpath:/templates/  #prefix：指定模板所在的目录
 check-template-location: true  #check-tempate-location: 检查模板路径是否存在
 cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
 suffix:  .html
 #encoding: UTF-8
 #content-type: text/html
 mode: HTML5

